/* permod/LoParser.cpp */
/* Parse log file generated by Macker. */

#include "permod/LogParser.h"
#include <llvm/Support/Error.h>
#include <llvm/Support/MemoryBuffer.h>
#include <llvm/Support/raw_ostream.h>
#include <sstream>

namespace permod {

LogParser::LogParser(const std::string &FileName) : InputFileName(FileName) {}

void LogParser::parse() {
  auto BufferOrError = llvm::MemoryBuffer::getFile(InputFileName);
  if (!BufferOrError) {
    llvm::errs() << "Error opening input file: " << InputFileName << "\n";
    return;
  }

  std::string Line;
  bool IsHeader = true;
  std::istringstream Stream(BufferOrError.get()->getBuffer().str());

  while (std::getline(Stream, Line)) {
    if (IsHeader) {
      IsHeader = false; // Skip the header line
      continue;
    }

    // Handle CSV entries including newlines
    while (std::count(Line.begin(), Line.end(), ',') < 5) {
      std::string NextLine;
      if (std::getline(Stream, NextLine)) {
        Line += "\n" + NextLine;
      } else {
        llvm::errs() << "Malformed CSV line: " << Line << "\n";
        break;
      }
    }

    // Split the line into components
    std::istringstream LineStream(Line);
    std::string FileName, LineNumber, FunctionName, EventType, Content,
        ExtraInfo;

    std::getline(LineStream, FileName, ',');
    std::getline(LineStream, LineNumber, ',');
    std::getline(LineStream, FunctionName, ',');
    std::getline(LineStream, EventType, ',');
    std::getline(LineStream, Content, ',');
    std::getline(LineStream, ExtraInfo, ',');

    if (LineNumber.empty() ||
        !std::all_of(LineNumber.begin(), LineNumber.end(), ::isdigit)) {
      llvm::errs() << "Invalid or empty LineNumber: " << LineNumber
                   << " in line: " << Line << "\n";
      continue;
    }

    int LineNum = std::stoi(LineNumber);

    ParsedLogs.push_back(
        {FileName, LineNum, FunctionName, EventType, Content, ExtraInfo});
  }

  llvm::outs() << "Parsed logs from " << InputFileName << "\n";
}

const std::vector<macker::LogManager::LogEntry> &
LogParser::getParsedLogs() const {
  return ParsedLogs;
}

} // namespace permod